create table solar as
SELECT /*+ LEADING (EE) USE_HASH(EE) FULL(E) */ E.EVENT_TYPE_ID,
 E.X512_9 FROM APE1_RATED_EVENT PARTITION(C17_I12_S774) E , 
(SELECT EVENT_TYPE_ID FROM (SELECT DISTINCT (EVENT_TYPE_ID), ROW_NUMBER () OVER (PARTITION BY EVENT_TYPE_ID ORDER BY EVENT_TYPE_ID ) 
UNIQ FROM APE1_EVENT_TO_EXT_REC WHERE EXTERNAL_RECORD_TYPE_ID IN (63, 78, 28, 109, 31, 
138, 73, 134, 132, 110)) EE WHERE UNIQ=1 ) EE
 WHERE EE.EVENT_TYPE_ID = E.EVENT_TYPE_ID AND E.CYCLE_CODE = 17 AND E.CYCLE_INSTANCE = 12 
 AND E.CYCLE_YEAR = 2010 AND E.EVENT_STATE <> 'X' AND (SYS_UPDATE_DATE >= TO_DATE('20000101000000' , 'YYYY-MM-DD HH24:MI:SS'));

